services:
  postgres:
    image: postgres:17
    container_name: yt-playlist-vault-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: yt_playlist_vault
      POSTGRES_USER: yt_playlist_vault
      POSTGRES_PASSWORD: yt_playlist_vault
    volumes:
      - postgres_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:4.3.2-management
    container_name: yt-playlist-vault-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: yt_playlist_vault
      RABBITMQ_DEFAULT_PASS: yt_playlist_vault
      RABBITMQ_DEFAULT_VHOST: yt_playlist_vault
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  redis:
    image: redis:8.0-alpine
    container_name: yt-playlist-vault-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:
