spring:
  application:
    name: yt-playlist-vault

  datasource:
    url: jdbc:postgresql://localhost:5432/yt_playlist_vault
    username: yt_playlist_vault
    password: yt_playlist_vault

  data:
    redis:
      repositories:
        enabled: false

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
              - https://www.googleapis.com/auth/youtube.readonly

  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true
          initial-interval: 1s
          multiplier: 2
          max-interval: 10s
          max-retries: 3

app:
  cache:
    youtube-playlists:
      ttl: PT5M
  snapshot-scheduler:
    enabled: true
    fixed-delay: PT72H
    initial-delay: PT1M
